### ISSUE TITLE
Pick SBML model

### ISSUE THREAD

**Issue by jessvasseur** [ahodelin/Bachmann_Archive#10]
- compare different versions of existing SBML models
- select best version to be used for simulation

**Comment by jessvasseur** [comment]
some SBML models might already be linked to a simulation (SED-ML, COPASI) which would make our lives a little easier :) e.g. https://www.ebi.ac.uk/biomodels/BIOMD0000000861

**Comment by fphans** [comment]
hotline zu @JessicaVasseur123 und @ohoelske wird aktiviert. Entscheidung XML-file ist gefallen, doku dazu läuft

**Comment by fphans** [comment]
https://github.com/ahodelin/Bachmann_Archive/blob/main/model/Bachmann2011.xml

https://github.com/ahodelin/Bachmann_Archive/wiki/Comparison-of-SMBL-models
