### ISSUE TITLE
Pick software tool(s) for simulation

### ISSUE THREAD

**Issue by jessvasseur** [ahodelin/Bachmann_Archive#11]
- compare tools supporting SED-ML (import & export)

**Comment by jessvasseur** [comment]
http://sed-ml.org/showcase.html

**Comment by jessvasseur** [comment]
https://tellurium.readthedocs.io/en/latest/notebooks.html#working-with-sed-ml
http://sysbioapps.spdns.org/SED-ML_Web_Tools

**Comment by fphans** [comment]
both tools added to the [toolbox](https://github.com/ahodelin/Bachmann_Archive/wiki/Toolbox)

**Comment by jessvasseur** [comment]
(1) create default simulation in SED-ML WebTools based on SBML model, then use COPASI to reproduce specific figures
(2) reproduce all simulation experiments using Tellurium
