### ISSUE TITLE
Generate SED-ML files

### ISSUE THREAD

**Issue by jessvasseur** [ahodelin/Bachmann_Archive#14]
- build SED-ML files for selected experiments based on SBML model selected by Group 2
- test generated SED-ML files (e.g. using a different tool)

**Comment by jessvasseur** [comment]
completed:
- default simulation (using SED-ML WebTools)
- Fig4, SuppFig9 (using Tellurium)

**Comment by ohoelske** [comment]
Test SWT and COPSI works fine, tellurium will be tested next.

**Comment by jessvasseur** [comment]
initial generation of SED-ML files is completed - they will now be optimized (#65) and integrated into the COMBINE archive (#15). For figures that could not be reproduced, separate issues will be opened with more details for future reference
