### ISSUE TITLE
Integrate SED-ML into COMBINE-Archive

### ISSUE THREAD

**Issue by jessvasseur** [ahodelin/Bachmann_Archive#15]
- add generated SED-ML files and any output to COMBINE-Archive

**Comment by ohoelske** [comment]
Proposing tellurium for this task @JessicaVasseur123 section 4.5.1. in [https://readthedocs.org/projects/tellurium/downloads/pdf/latest/](url)

**Comment by jessvasseur** [comment]
@ahodelin could we get some help pushing the [/experiment](https://github.com/ahodelin/Bachmann_Archive/tree/main/experiment) and [/result](https://github.com/ahodelin/Bachmann_Archive/tree/main/result) folders into the COMBINE archive? I am a bit lost using CombineArchiveWeb and as mentioned in #30 it is currently not possible to simulate the archive.

**Comment by jessvasseur** [comment]
@ahodelin could you double check that the latest SED-ML files [commit 5407960](https://github.com/ahodelin/Bachmann_Archive/commit/540796001c865c6b89be2cc742ad750975b40ae3) have been added to the COMBINE archive? no further changes to the SED-ML files expected at this stage :)

**Comment by ahodelin** [comment]
all right, the new version is in the COMBINE archive

**Comment by ahodelin** [comment]
DONE!!!
