### ISSUE TITLE
Readme Überprüfen

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#17]
Hallo Zusammen,

Unser Readme ist Geboren!!

Es ist öffen für Vorschläge, Anmerkungen, Korrekturen, etc. 

Viel Spaß

**Comment by jessvasseur** [comment]
würde es nicht Sinn machen die Readme gleich auf Englisch zu erstellen?

**Comment by ahodelin** [comment]
100% Einferstanden, man muss an das Zukunftige Paper denken :-)

**Comment by lknegendorf** [comment]
Ich finde es super so!

**Comment by lknegendorf** [comment]
> Ich finde es super so!

Vielleicht kann man hier dann auch noch den Citation Style entsprechend anpassen, siehe #22

**Comment by jessvasseur** [comment]
Citation Style ist angepasst (vielleicht nochmal drüber schauen) - ansonsten kann das Issue von mir aus geschlossen werden
