### ISSUE TITLE
Language for documentation

### ISSUE THREAD

**Issue by jessvasseur** [ahodelin/Bachmann_Archive#18]
documentation in English or German? maybe English for GitHub and any files in the repository but German for the documentation templates (since this will be our project work to submit at the end of the course).

but it is all up to the project coordination team :) 

- if German please ignore / close / delete this issue
- if English please translate the [documentation template](https://docs.google.com/document/d/1VbH5wR7OgKDuilCbdsq0GDnomxUXsWYA5evIXJEKO8E/edit#heading=h.4zoyt3gojn0h)

**Comment by ahodelin** [comment]
English in GitHub and German in another documents

**Comment by leoplue** [comment]
Why would we chose to document in different language? Wouldn't it be nice to re-use some text blocks from our Wiki in our Hausarbeit?

**Comment by jessvasseur** [comment]
I agree that it would make things easier to use the same language everywhere. Maybe worth checking with Dagmar if the Hausarbeit could be prepared in English?

**Comment by AMB-Git-Hub** [comment]
Hi, gibt es hier andere Meinungen oder sind alle d'accord? dann würden wir das schließen @ohoelske @fphans @lknegendorf @fschoenecker

**Comment by fschoenecker** [comment]
Hi, ist für mich OK. Haben wir schon Rückmeldung von Dagmar bzgl. Hausarbeit?

**Comment by jessvasseur** [comment]
E-Mail an Dagmar ist gerade erst raus - ich sage Bescheid, wenn sie sich meldet

**Comment by ohoelske** [comment]
Would prefer English.

**Comment by lknegendorf** [comment]
> Would prefer English.

Same

**Comment by jessvasseur** [comment]
Dagmar sieht kein Problem damit alles auf Englisch zu machen.
@ahodelin / @AMB-Git-Hub passt ihr das Template an?

**Comment by fphans** [comment]
check
