### ISSUE TITLE
Provide useful file formats for COMBINE Archive

### ISSUE THREAD

**Issue by leoplue** [ahodelin/Bachmann_Archive#21]
see tip 8 of 10 tips paper suggested by Dagmar

**Comment by leoplue** [comment]
suggestion: 
[SBGN-ML 0.2](https://normsys.h-its.org/format?form%5Bid%5D=16)
[SBGN-ML 0.3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7756621/)
NWT
PNG
SVG

celldesigner export not working?? 


if you have improvements for suggestion, please update wiki! 😸

**Comment by lknegendorf** [comment]
SBGN-ML 0.3 Not working, will update Wiki later
