### ISSUE TITLE
Citation style in der Dokumentation / Wiki

### ISSUE THREAD

**Issue by lknegendorf** [ahodelin/Bachmann_Archive#22]
Moin, ich denke es ist sinnvoll, einen einheitlichen Referenzstil festzulegen für die Dokumentation:
Habe unsere erste Seite mal aufgebaut und hier einfach etwas genommen, kann ich dann gerne anpassen: https://github.com/ahodelin/Bachmann_Archive/wiki/SBGN_Maps

Ist sicherlich im Hinblick auf ein mögliches paper noch sinnvoll, die Referenzen zentral im Repo zu sammeln. Vielleicht kann man eine .bibtex Datei erstellen, in die jeder die Referenzen integrieren kann?

**Comment by ahodelin** [comment]
Du bist der 1. dann machen wir alle wie du :-)

Beispiel für den Rest

## References
**[1]** Schölzel, C., Blesius, V., Ernst, G. _et al._ Characteristics of mathematical modeling languages that facilitate model reuse in systems biology: a software engineering perspective. npj _Syst Biol Appl_ **7**, 27 (2021). [https://doi.org/10.1038/s41540-021-00182-w](https://doi.org/10.1038/s41540-021-00182-w)

**Comment by leoplue** [comment]
Welcher citation style ist das, @lknegendorf? 

BibTex ist hinzugefügt.

**Comment by lknegendorf** [comment]
> Welcher citation style ist das, @lknegendorf?
> 
> BibTex ist hinzugefügt.

Das ist der von Nature ;) https://www.nature.com/nature/for-authors/formatting-guide

Für BibTeX ist das "naturemag": https://www.bibtex.com/s/bibliography-style-nature-naturemag/

**Comment by fphans** [comment]
how to sync this .bib-file with citavi project?

**Comment by leoplue** [comment]
@fphans Not using citavi since I don't have a licence. Have you tried [this](https://www1.citavi.com/sub/manual5/de/importing_a_bibtex_file.html)?

**Comment by lknegendorf** [comment]
> how to sync this .bib-file with citavi project?

If Tanias Help Article is not working, here is another Option from the Citavi Help Webpage:

BibTeX-Datei in Citavi importieren
Öffnen Sie das Citavi-Projekt, in das Sie Ihre Daten importieren möchten.
Wählen Sie in Citavi aus dem Menü Datei den Befehl Importieren.
Wählen Sie die Option aus einer Textdatei. Klicken Sie auf Weiter.
Wählen Sie die Option BibTeX. Klicken Sie auf Weiter.
Klicken Sie auf Durchsuchen, um die bib-Datei auszuwählen, die Sie aus Zotero exportiert hatten. Klicken Sie auf Öffnen und Weiter.
Der Import startet. Klicken Sie auf Titel übernehmen.

**Comment by lknegendorf** [comment]
Arbeite zwar weder mit Citavi noch mit Zotero aber das BibTeX Format ist eigentlich ein generischer Standard.

**Comment by jessvasseur** [comment]
die Frage war auch, ob wir die Quellen in der BibTeX Datei im Wiki automatisch nutzen können in anderen Einträgen? oder ob man die Quellenangaben in den einzelnen Wiki-Einträgen manuell bauen muss?
unterstützt GoogleDocs BibTeX (für die Dokumentation/Hausarbeit)?

**Comment by fphans** [comment]
Vll habe ich mich unsauber ausgedrückt. Bibtex erzeugen ist kein Problem. Das kann jedes Literaturverwaltungsprogramm oder auch Jabref o.ä als complier. Ich habe das .bib-file im gite repo gefunden und micht gefragt, wie man das am besten administeritert, da ja weder im wiki darauf referenziert werden kann, noch bei referenzen , die man im wiki hinzufügt das bib-file aktualisiert wird.

Sollte das bib- file lediglich als "referenzsammlung" diensen müssen wir ganz am ende noch mal händisch alle referenzen aus den artikeln einsammeln und eine neues, finales .bib-file bauen.

**Comment by fphans** [comment]
> die Frage war auch, ob wir die Quellen in der BibTeX Datei im Wiki automatisch nutzen können in anderen Einträgen? oder ob man die Quellenangaben in den einzelnen Wiki-Einträgen manuell bauen muss?
> unterstützt GoogleDocs BibTeX (für die Dokumentation/Hausarbeit)?
Für Arbeit mit bibtex / latex kann man auch gut in [overleaf](https://de.overleaf.com/) zusammenarbeiten (für die HA)

**Comment by lknegendorf** [comment]
> Vll habe ich mich unsauber ausgedrückt. Bibtex erzeugen ist kein Problem. Das kann jedes Literaturverwaltungsprogramm oder auch Jabref o.ä als complier. Ich habe das .bib-file im gite repo gefunden und micht gefragt, wie man das am besten administeritert, da ja weder im wiki darauf referenziert werden kann, noch bei referenzen , die man im wiki hinzufügt das bib-file aktualisiert wird.
> 
> Sollte das bib- file lediglich als "referenzsammlung" diensen müssen wir ganz am ende noch mal händisch alle referenzen aus den artikeln einsammeln und eine neues, finales .bib-file bauen.

Ok, got it. Sorry for the misunderstandings ;)
Let's discuss in the weekly later
