### ISSUE TITLE
Ordner references in documentation oder bib-Datein in documentation

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#24]
Hallo,

wir sollen die COMBINE-Struktur wie im Paper [Scharm, M. and Waltemath, D.](https://f1000research.com/articles/5-2421/v1), Sektion "**Organising the COMBINE archive**" beibehalten. Auf diesem Grund sollte entweder (Vorschlag 1) der Ordner **references** mit Inhalt in dem Ordner **documentation**  oder  (Vorschlag 2) die bib-Datein direkt in dem Ordner **documentation** gespeichert werden.

- Vorschlag 1: documentation/references/SystemsBiology.bib
- Vorschlag 2: documentation/SystemsBiology.bib

Danke und Grüße

PS: Bitte auch an die andere Teilnehmer oder Teilnehmerinnen, die die bib-Datei nutzen nach der Änderung Bescheid geben.

**Comment by fphans** [comment]
kann man das mit unserem citavi projekt verknüpfen?
