### ISSUE TITLE
Review Wiki Group 1

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#25]
Hi,

du solltest unser Teil der Wiki überprüfen.

Ich habe unter anderen die Formatierung in der Sektion "Provision of a tamplate for documentation" etwas gestaltet und den Inhalt in "Communication Channels" mit Information befühlt.

Grüße

Abel

**Comment by fphans** [comment]
core elements from the google sheet "Communication Channels" has been integrated in the [toolbox](https://github.com/ahodelin/Bachmann_Archive/wiki/Toolbox)
