### ISSUE TITLE
img insertion

### ISSUE THREAD

**Issue by fphans** [ahodelin/Bachmann_Archive#26]
dear colleagues

if find git behaving differently than I am used to when trying to insert images. The only option is insertion by URL which leaves out the pasting from the clipboard for screenshots etc.

is that a general setting that @ahodelin could just activate?

asking for a friend

**Comment by jessvasseur** [comment]
seems to be complicated for some reason - this might work https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Add-images-to-the-Wiki (option via empty issue)

**Comment by fphans** [comment]
👍
