### ISSUE TITLE
Our COMBINE Archive!!!

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#27]
Hello,

hier is our COMBINE archive in testversion: [id: 2e2f8798-aec7-40a1-b49b-62b3ec80fac2](https://cat.bio.informatik.uni-rostock.de/rest/share/6b507398-c103-4b92-9c90-d6b105ff1372)
Here the link again: https://cat.bio.informatik.uni-rostock.de/rest/share/6b507398-c103-4b92-9c90-d6b105ff1372

I need some info:
- What model(s) did you use in your group? [SBML and Extra Files](https://github.com/ahodelin/Bachmann_Archive/wiki/Extra_Formate)
  - bachmann.xml - JWS Online
  -  BIOMD0000000347_url.xml - BioModels (Bachmann2011_JAK2-STAT5_FeedbackControl)
  - Bachmann2011.xml - BioModels (Bachmann2011 - Division of labor by dual feedback regulators controls JAK2/STAT5 signaling over broad ligand range)
- Files for the experiment folder
  - please upload these files in Google Drive here [experiment](https://drive.google.com/drive/folders/1ILvSqvn-2IeRo6WQmb-EIiwQGmICCSuq)
- Files for the result folder
  - please upload these files in Google Drive here [result](https://drive.google.com/drive/folders/1QLkRVQ3lLV1UrhrWQ7i7wD7cvbzhlFiL)

Name convention for files in eperiment/result:
  **nameOfSBMLFromSource_yyyymmdd.some_extension**
  - yyyy = four digits for year. Example, 2021
  - mm = two digits for month. Example, 06
  - dd = two digits for day. Example, 08, 31

Some examples
- From JWS Online: **bachmann_20210620.png**
- From BioModels (Bachmann2011 - Division of labor by dual feedback regulators controls JAK2/STAT5 signaling over broad ligand range): **Bachmann2011_20210620.etc**

Thanks

**Comment by jessvasseur** [comment]
initial SED-ML files and results were added to github yesterday - do we still need to upload them on GoogleDrive? 

SED-ML files were generated using https://github.com/ahodelin/Bachmann_Archive/blob/main/model/Bachmann2011.xml. If this file is renamed we need to update the SED-ML files and the underlying tellurium scripts...

**Comment by jessvasseur** [comment]
do we really need the naming convention? I think our experiment and results files are clearly named.. maybe to discuss later today.

**Comment by ahodelin** [comment]
That is because wi have three different models in our repository and we need to know which were used for the experiments and results.

**Comment by jessvasseur** [comment]
all experiments and results were created using this [model](https://github.com/ahodelin/Bachmann_Archive/blob/main/model/Bachmann2011.xml) - the one chosen by Group 2. The SED-ML files contain a link to this model and I have included a txt file in each results folder with a short description regarding which model, which SED-ML file, which tool was used.

In my opinion all other model files could be deleted or put in a subfolder (other models) to avoid any confusion

**Comment by ahodelin** [comment]
Ok, thanks for the info

**Comment by jessvasseur** [comment]
the link to the COMBINE archive above is not working for me - any idea why?

**Comment by ahodelin** [comment]
Sorry, the COMBINE Web is not too intuitive, and I have posted the link without to share, here the shared link:

https://cat.bio.informatik.uni-rostock.de/rest/share/6b507398-c103-4b92-9c90-d6b105ff1372

There is a link with the name ::ba, this is our archive.

**Comment by fphans** [comment]
would recommend pushing all "unused" model files to a subfolder from "models". baybe itbecomes more clear on what code we simulate and what parts are only mentioned for integrity

**Comment by fphans** [comment]
respective conventions: 
there is a  DCMI terminology in the sbml file (e.g. dcterms:W3CDTF describing the set of dates and times constructed according to the W3C Date and Time Formats Specification.)
 some details are already in the [wiki](https://github.com/ahodelin/Bachmann_Archive/wiki/Metadata_G2)

**Comment by jessvasseur** [comment]
@ahodelin could you update the COMBINE archive with the added / modified files for experiments and results? thank you :)
