### ISSUE TITLE
orcid-affiliation

### ISSUE THREAD

**Issue by fphans** [ahodelin/Bachmann_Archive#29]
dear high flyers
I added some member information to the wiki of every group. Mostly I connected with the respective [ORCID-ID](https://orcid.org/). As some of you gifted colleagues  (@tanialue , @marisakaup) do not have an ORCID-IDI want to clarify if you wish to have other platforms linked as can be seen in the members page of group 3?

**Comment by fschoenecker** [comment]
thanks for asking. current link is fine by me

**Comment by marisakaup** [comment]
Hi @fphans , I have registered at ORCID https://orcid.org/0000-0002-6125-9302

**Comment by fphans** [comment]
prof. kaup changed to orcid linkin group 3 wiki

**Comment by fschoenecker** [comment]
Hi @fphans, finally made it to orcid https://orcid.org/0000-0001-7588-2851

**Comment by fphans** [comment]
@fschoenecker , ist eingearbeitet.
@tanialue , was ist Dein plan?

**Comment by fphans** [comment]
all done
