### ISSUE TITLE
archive not operational

### ISSUE THREAD

**Issue by fphans** [ahodelin/Bachmann_Archive#30]
![image](https://user-images.githubusercontent.com/77018941/122669797-43b7a680-d1bf-11eb-99fa-d290afb33a12.png)
 cant simulate on current archive on https://cat.bio.informatik.uni-rostock.de/#archive/2e2f8798-aec7-40a1-b49b-62b3ec80fac2

**Comment by jessvasseur** [comment]
https://cat.bio.informatik.uni-rostock.de/rest/share/6b507398-c103-4b92-9c90-d6b105ff1372 functional link to archive

the files from /experiments and /results are not yet included, hence no simulation possible yet

**Comment by fphans** [comment]
💡

**Comment by jessvasseur** [comment]
@ahodelin see #15 - we need some help to get the experiments etc. into the COMBINE Archive - thank you :)

**Comment by ahodelin** [comment]
@JessicaVasseur123: experiment files are in COMBINE Archive
@fphans: the simulation is now possible

I will upload the result files

**Comment by jessvasseur** [comment]
perfect thank you! simulation works fine in general - the archive contains several sedml files but only the first one is simulated by default.
