### ISSUE TITLE
Ergebnisse Metadaten

### ISSUE THREAD

**Issue by fphans** [ahodelin/Bachmann_Archive#33]
Übersicht der Metadaten
Bewertung
Links zu den Metadaten-Dateien

**Comment by fschoenecker** [comment]
HI @fphans,
i wonder if this is still todo (should i add something herehttps://github.com/ahodelin/Bachmann_Archive/wiki/Metadata_G2 ?)

**Comment by fphans** [comment]
this must be my evil twin having posted here. I have no idea what this means
