### ISSUE TITLE
COMBINE Archive almost ready

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#34]
Hello!!

I have uploaded all files in our COMBINE Archive and it is almost ready!!! :-)

please visit the link: https://cat.bio.informatik.uni-rostock.de/rest/share/6b507398-c103-4b92-9c90-d6b105ff1372 , click on ::bachmann and simulate

**Comment by lknegendorf** [comment]
@ahodelin Our SBGN folder is still missing, but we are working on it!

**Comment by ohoelske** [comment]
Looks great, well done.

**Comment by ahodelin** [comment]
Our COMBINE Archive is updated with the new GitHub modifications

**Comment by fphans** [comment]
@ahodelin 
close?
