### ISSUE TITLE
Simulation without DefaultSimulation.sedml

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#36]
Hi,

I have tested the simulation in our COMBINE Archive without the file DefaultSimulation.sedml, I have saved a html of the  simulation in our Google Drive here: https://drive.google.com/drive/folders/1EQrSg4P415bpMkmtl8crlY5R2eQ-zN_K 
Is the result OK?

**Comment by ohoelske** [comment]
The HTML you are refering to is reproducing Supp Figure 9.

**Comment by ahodelin** [comment]
Hi,

if you want, you can delete the other simulations from the Repo (DefaultSimulation.sedml, Fig4.sedml) and the python sript SEDML_Fig4_v2.ipynb.

**Comment by fphans** [comment]
didnt we agree we keep the thellurium script in the archive?

**Comment by ahodelin** [comment]
@fphans there are two thellurium scripts in the repo right now, one for each simulation, Fig 4 and Fig 9. My idea is to have only the simulation and the tellurium script for Fig 9. It is better for the documentation too, because @ohoelske and @JessicaVasseur123 don't need to describe two simulations.

**Comment by jessvasseur** [comment]
@ahodelin the other files need to stay, including the python scripts (as documentation). even though only one file is actually used when simulating the archive via CombineArchiveWeb (SuppFig9 I think), the other files are still available for download via the repo or via the archive.
the goal is to have a simulation (SED-ML file) for each figure in the paper (plus the default one). we are currently working on the remaining figures (3 / 5 / 6); if time allows we will also try to combine all figures into one SED-ML file.

**Comment by jessvasseur** [comment]
just for clarification: the python scripts are just there to document the generation and testing of the SED-ML files using tellurium, but are not actually used for the simulation.
