### ISSUE TITLE
glossar

### ISSUE THREAD

**Issue by fphans** [ahodelin/Bachmann_Archive#44]
Das Glossar im g-drive wurde auch nochmal umfänglich ergänzt über das Wochenende und auf der introduction Seite im Wiki verlinkt. wer noch spezielle Abkürzungen oder softwaretools / Standards aus den Gruppenarbeiten dort einpflegen kann immer gerne

**Comment by ahodelin** [comment]
look at issue #46

**Comment by fphans** [comment]
merge into #46
