### ISSUE TITLE
Repro_Figure3

### ISSUE THREAD

**Issue by ohoelske** [ahodelin/Bachmann_Archive#45]
[Repro Figure 3](https://colab.research.google.com/drive/1u41-ruSuNHK7ZsypWl-v8ICIu8jwYJU-?usp=sharing) using Tellurium 

Not solved issues: 

1. Axis units not in accordance to paper
2. tSTAT5 not defined in model
3. Export as SED-ML

**Comment by jessvasseur** [comment]
SED-ML file was generated and exported in new notebook ([Link](https://drive.google.com/file/d/1N_Vn8QtOnEUjDQ0Bj3Fk6N84zREBIpbG/view?usp=sharing))

**Comment by jessvasseur** [comment]
axis units are a general issue with the plots - I think we would need to implement some kind of conversion factor (probably specified in the Supplementary Information)

**Comment by jessvasseur** [comment]
further discussions regarding the figures in #14
