### ISSUE TITLE
Glossary from Google to Wiki

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#46]
Hello,

I have imported our glossary from Google Doc into our Wiki (https://github.com/ahodelin/Bachmann_Archive/wiki/glossary).
 **If you want**, you can translate something.

Thanks

**Comment by ahodelin** [comment]
How to for the curious!! (it works in Linux)

1. Download table of glosary as table with tab (.tsv)
2. in command line 
  2.1 cd folder with file.tsv
  2.2 sed  -i 's/^/|/' file.tsv # insert "|" at the beginning of the lines
  2.3 sed  -i 's/\t/|/g' file.tsv # replace all tab delimiter in a line by  "|"
  2.4 sed  -i 's/\r//' file.tsv # remove the carriage Return from Windows format
3. Open file.tsv wit any text editor an insert |-|-|... into the second line.
4. Select all text and copy.
5. Paste into Wiki page.

Thats all!!

**Comment by ahodelin** [comment]
Extension of issue #44

**Comment by fphans** [comment]
shall we change the link on the wiki landing page according to the transfer or keep the google link live?

**Comment by jessvasseur** [comment]
> shall we change the link on the wiki landing page according to the transfer or keep the google link live?

I would change the link to the glossary in the wiki - maybe include a link to Google at the end as a reference

**Comment by ahodelin** [comment]
Don't forget ,the repository has a CC0 license, we shouldn't have any link to a side without public access. We could keep the glossary or delete it if it is too long.

**Comment by jessvasseur** [comment]
the glossary file in GoogleDrive is available to view and comment for anyone I think

**Comment by ahodelin** [comment]
Good idea
