### ISSUE TITLE
Final Note = Wiki

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#50]
Hello

as some of you know, the note of this modul (Dagmar & Clemens) is our Wiki. Please do your best with the documentation.

We have till **04.07.2021**

Thanks

**Comment by fphans** [comment]
when I am doing my best usually something terrible happens :baby_bottle:

**Comment by lknegendorf** [comment]
Group 3 is done :tada: 💯

**Comment by jessvasseur** [comment]
Group 4 as well 🎉
