### ISSUE TITLE
Load Omex file in tellurium

### ISSUE THREAD

**Issue by ohoelske** [ahodelin/Bachmann_Archive#53]
Run omex file from CombineArchive in tellurium

[tellurium doku](https://tellurium.readthedocs.io/en/latest/notebooks.html#combine-inline-omex) 

@JessicaVasseur123

**Comment by jessvasseur** [comment]
done - see [Google Drive](https://drive.google.com/drive/folders/1K8gYBPEHrd8jsOZXD1T4c7r--McsYoT2)
