### ISSUE TITLE
Upload repo into COMBINE Archive

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#59]
Hello,

Thanks so much you all for the super work!!

I will upload our repo into COMBINE Archive at **15:30** for our presentation at 20:00.
1. @lknegendorf, @marisakaup, @tanialue - Do you need to make another modifications?
2. @JessicaVasseur123, @ohoelske - As you know COMBINE take the file DefaultSimulation.sedml for the simulation by default. Should I remove this file from the repository to keep only our generated files? 
3. @JessicaVasseur123, @ohoelske - In think, one of you uses a Mac, it means some .DS_Store files were generated and are in our repo. These files are hidden in Mac because they have a "." at the beginning. I think we do not need such files. What do you think about it?
4. I think we should have only our files and the model Bachmann2011.xml in our repo and COMBINE Archive for a possible further publication #56 and to avoid misunderstood.

Best

Abel

**Comment by jessvasseur** [comment]
@ahodelin
2. I would leave the DefaultSimulation.sedml in the repo and the COMBINE archive for now. Anyone looking to reproduce a specific experiment would have to download and extract the archive in any case to get to the correct SED-ML file
3. that's me sorry - I only noticed this after committing and pushing my changes last night using GitHub Desktop (they are hidden in Finder) and was too sleepy to remove them. They can definitely be deleted.

**Comment by jessvasseur** [comment]
what do you mean exactly by 4.? I think the files [Bachmann2011.cps](https://github.com/ahodelin/Bachmann_Archive/blob/main/model/Bachmann2011.cps) and [Bachmann2011.sedml](https://github.com/ahodelin/Bachmann_Archive/blob/main/model/Bachmann2011.sedml) from the model folder can be deleted, they are from the original biomodels entry

**Comment by lknegendorf** [comment]
@ahodelin thank you! We would provide the final structure of the files until about one hour. Maybe we will update three of the colored files after that, but I am confident we will have those ready by 15:30 p.m.

**Comment by ahodelin** [comment]
@JessicaVasseur123 by 4. that was my idea too, to delete Bachmann2011.cps and Bachmann2011.sedml I had deleted those file but after a pull requests and merge they were in the main repo again.

I will clone/update the main branch and delete the files Bachmann2011.cps and Bachmann2011.sedml before I update the COMBINE Archive.

**Comment by jessvasseur** [comment]
@ahodelin perfect thank you - feel free to delete any .DS_STORe files as well, otherwise I will take care of this later

our SED-ML files in ../experiment and outputs in ../result are done for now. We might be adding results from validation and testing of the COMBINE archive itself at a later stage if that is ok

**Comment by marisakaup** [comment]
@ahodelin We have merged final structure for SBGN.

**Comment by ahodelin** [comment]
@JessicaVasseur123, @ohoelske What is the difference between copasi_genaration and copasi_test?

**Comment by ohoelske** [comment]
@ahodelin @JessicaVasseur123 
SEDML file  generated in COPASI and produced figures in folder (Copasi_generation).
SEDML file generated in tellurium AND Validated in COPASI produced figures in folder (Copasi_test).

In general, generation is the tool which generated the SEDML and test is another SEDML tool to "Validate/test" (increase reproducibility)

**Comment by ahodelin** [comment]
@tanialue, @marisakaup, @lknegendorf The document BachmannPD_vanted.xml and BachmannPD_vanted.sbgn are the same (confirmed with the commands cmp and diff in Linux) and I can only one of them upload because the CombineArchiveWeb throws the error **"Unknown Error: Cannot upload file."** If ok, I upload the file BachmannPD_vanted.sbgn in the COMBINE Archive

**Comment by lknegendorf** [comment]
> @tanialue, @marisakaup, @lknegendorf The document BachmannPD_vanted.xml and BachmannPD_vanted.sbgn are the same (confirmed with the commands cmp and diff in Linux) and I can only one of them upload because the CombineArchiveWeb throws the error **"Unknown Error: Cannot upload file."** If ok, I upload the file BachmannPD_vanted.sbgn in the COMBINE Archive

Yes, totally. Thank you!
