### ISSUE TITLE
Literature format

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#62]
Please use the same reference format as in Readme etc.

Example:
bla bla ([[1]](https://doi.org/10.1038/msb.2011.50)).

**[1]** Scharm, M. and Waltemath, D. A fully featured COMBINE archive of a simulation study on syncytial mitotic cycles in Drosophila embryos. _F1000Research_ **5**, 2421 (2016). [https://doi.org/10.12688/f1000research.9379.1](https://doi.org/10.12688/f1000research.9379.1)

Thanks

**Comment by fphans** [comment]
verstehe ich nicht. haben wir da was anderes gemacht?
