### ISSUE TITLE
One day without issues is a good day!! :-)

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#69]

**Comment by jessvasseur** [comment]
can we open issues for RNASeq as well???

**Comment by ahodelin** [comment]
Yes, good idea!!

**Comment by fphans** [comment]
[hier?](https://github.com/fphans/BIDS-NGS)

**Comment by ohoelske** [comment]
Hat jemand Lust auf einen Hackathon in den nächsten Tagen?

**Comment by jessvasseur** [comment]
> Hat jemand Lust auf einen Hackathon in den nächsten Tagen?

oder Nächten? ;)

**Comment by fphans** [comment]
klar fr sa so ab 20:30

**Comment by jessvasseur** [comment]
ich setze mich heute Abend dran, wenn die Kinder schlafen - mit der Hoffnung dass Sa und So dann ausnahmsweise mal frei sind :)
