### ISSUE TITLE
XMLs from result/Validation/Test_SWT_2021-06-28/[Supp]Fig* not in COMBINE Archive

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#72]
Hello,

I have updated our COMBINE Archive but I can't upload the XML files from https://github.com/ahodelin/Bachmann_Archive/tree/main/result/Validation/Test_SWT_2021-06-28 into our COMBINE Archive. It throws this error: "Unknown Error: Cannot upload file". 
As you know the web interface is a bit cryptic and I don't know why I can't upload these files. 
I have uploaded the other files and I performed a simulation and it works without problems.
We have two options.
1. I document this problem in my wiki section reproducibility.
2. We delete such files from our repo (I don't like this option)

Best regards

Abel

**Comment by jessvasseur** [comment]
thanks for uploading all the latest additions :) I just tried to add the xml files (which contain the results of the simulation in SWT in addition to the plots) as well, but get the same error

I would keep the files in the repo and document the problem somewhere (maybe another issue for the CombineArchiveWeb people?)

option 3 would be to convert xml to csv and add that instead but not sure how to do this quickly. I know there are plenty of online converters, I will give it a try.

**Comment by ahodelin** [comment]
I had made some issues for the CombineArchiveWeb one of them is the description of our problem: (https://github.com/SemsProject/CombineArchiveShowCase/issues/16) with the problem.
Don't forget, you have worked very hard, tray the conversion only if you have time. ;-)
