### ISSUE TITLE
Remember Results & Discussion / Limitations?

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#79]
Hello,

some of you want to write into sections "Results" and "Discussion / Limitations". 
At the moment are those sections empty... 

Best regards 
Abel

**Comment by fphans** [comment]
Samstag dann...

**Comment by jessvasseur** [comment]
same here - auf jeden Fall vor Sonntag 23:59

**Comment by fphans** [comment]
performed minor changes

**Comment by jessvasseur** [comment]
added and extended some discussion / limitations from Group 4

**Comment by lknegendorf** [comment]
Added paragraph for group 3 (only two aspects relevant for the whole project, not too much in detail). 
Added issue to Newt Repo https://github.com/iVis-at-Bilkent/newt/issues/679 and referenced that in the text, too.
