### ISSUE TITLE
Deadline for archive & wiki

### ISSUE THREAD

**Issue by jessvasseur** [ahodelin/Bachmann_Archive#82]
Should we set a deadline for updating files in the repo and working on the wiki tomorrow? Just to give @ahodelin time to finalise the COMBINE archive and convert the wiki to a document (?).

**Comment by fphans** [comment]
@fschoenecker & @fphans will be adding some minor changes to the annotation section tomorrow, no further changes are planned

**Comment by ahodelin** [comment]
Please no more changes in the folders **documentation, experiment, result** and **model**. I have uploaded the new version of our COMBINE archive

**Comment by jessvasseur** [comment]
update from Group 4: we will make some final changes to the wiki this afternoon (discussion, summary)
