### ISSUE TITLE
German Links in Wiki

### ISSUE THREAD

**Issue by lknegendorf** [ahodelin/Bachmann_Archive#84]
@ahodelin  I recognized, that the landing pages of each group are named "Gruppe_n", I already changed this to "Group_3" for our group, I could also change the names for all groups into English, if you approve. But I guess your links to the group wikis will not work anymore in the issues then, so just wanted to ask first ;)

**Comment by ahodelin** [comment]
I do that ;-)

**Comment by ahodelin** [comment]
Done

**Comment by fphans** [comment]
mucho apreciado
