### ISSUE TITLE
Select appropriate language & document reasons

### ISSUE THREAD

**Issue by leoplue** [ahodelin/Bachmann_Archive#9]
"There are three orthogonal and complementary visual languages defined in SBGN: Process Description (PD), Entity Relationship (ER), and Activity Flow (AF). They can be seen as three alternative projections of the underlying, more complex biological information." (https://sbgn.github.io/specifications)

**Comment by lknegendorf** [comment]
https://github.com/ahodelin/Bachmann_Archive/wiki/3SBGN_Standard

**Comment by lknegendorf** [comment]
> https://github.com/ahodelin/Bachmann_Archive/wiki/3SBGN_Standard

@tanialue @marisakaup draft completed, please check!

**Comment by marisakaup** [comment]
From Quick Tip Publication

"The Systems Biology Graphical Notation (SBGN, [2]) is an international, established, and widely used standard to reduce the ambiguity in representations of biological maps. The community standard provides sets of well-defined symbols, each of them with a specific biological meaning. For example, a round-corner rectangle in an SBGN map represents a macromolecule. The SBGN offers the following three complementary languages to visually describe the biology: SBGN Process Descriptions (SBGN PD [11]), SBGN Entity Relationships (SBGN ER [12]), and SBGN Activity Flows (SBGN AF [13]). Metabolic maps depicting detailed biochemical reactions, state transitions, and transport are best represented with SBGN PD. Nonmechanistic influences between biological entities, such as signaling pathways and regulatory networks, are best highlighted in SBGN AF. Finally, SBGN ER visualises independent interactions between biological entities without any temporal aspect. Maps in SBGN ER are therefore useful to avoid combinatorial explosions resulting from multicomponent complexes and molecules with multiple states."

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005740

**Comment by lknegendorf** [comment]
https://github.com/ahodelin/Bachmann_Archive/wiki/Choice-of-SBGN-language
