### ISSUE TITLE
Preliminary Wiki in HTML format in Google drive

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/Bachmann_Archive#91]
Hello,

I have exported and uploaded a preliminary version of our Wiki in html format in our Google Drive. (https://drive.google.com/drive/folders/1SmUAruE4XomiF--7W5nUqcv1ChKmPZl5)
I think it is a good idea to have our work in a file :-)

Thanks and best regards

Abel

**Comment by jessvasseur** [comment]
@ahodelin when are you planning to create the final copy of the Wiki in HTML?

**Comment by ahodelin** [comment]
I think at 22:00

**Comment by fphans** [comment]
Everybody hand in the html in classroom?

**Comment by jessvasseur** [comment]
Yes, the final version tonight I guess
